config/routes.rb
Tapski::Application.routes.draw do
  root :to => "home#index"

  resources :listings do
    member do
      post 'rename'
    end
  end

  resources :identities
  match '/save_search', :to => "home#save_search"
  match '/mysearches', :to => "home#mysearches"
  match '/search_with_criteria', :to => "home#search_with_criteria"
  match '/get_search_details', :to => "home#get_search_details"
  match '/mylistings', :to => "listings#index"
  match '/profile', :to => "users#profile"
  resources :users
  match "/save_profile", :to => "users#save_profile"
  match "/login", :to => "sessions#new"
  match "/signout" => "sessions#destroy", :as => :signout
  match '/auth/:provider/callback',  to: 'sessions#create'
  match "/auth/failure", to: "sessions#failure"
  match '/auth/:provider/register',  to: 'users#create'
  match '/edit' =>  'users#edit_profile'
  match '/homesearch' => 'listings#home_search'
  match '/my_search_listing' => 'listings#my_search_listing'

  match '/get_listing_contact' => 'listings#get_contact'
  match '/show_image' => 'listings#show_image'
  match '/add_images' => 'listings#add_images'
  match '/upload_image' => 'listings#upload_image', :via => :post
  match '/messages' => 'users#messages'
  match '/reply_message' => 'users#reply_message'
  match '/send_message' => 'users#send_message'
  match '/delete_message' => 'users#delete_message'
  match '/vote_listing' => 'listings#vote_up'
  match '/remove_vote_listing' => 'listings#vote_remove'
  resources :mysearches

end

app/models/listing.rb
class Listing < ActiveRecord::Base
    has_many :pictures
    acts_as_votable
  attr_accessible :bathrooms, :name,:listing_type, :bedrooms, :costpersqft, :daysontapski, :laonpayment, :lotsize, :mls, :neighbourhood, :price, :squarefootage, :status, :adjustment_type, :yearbuilt,:description, :tap_description, :address_line1, :city, :address_line2, :state, :zip,:image_file,:lat, :long
  belongs_to :user

  def self.search(keyword)
    where('name ilike :keyword OR description ilike :keyword OR tap_description ilike :keyword', { :keyword => "%#{keyword}%" })
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  # GET /listingssession
  # GET /listings.json
  before_filter :require_login, :except => ['show','home_search','my_search_listing','get_contact','show_image']
  def index
    @user = User.find(session[:user_id])
    puts @user.inspect
    @listings = @user.listings.all(:order => 'created_at DESC')
    puts @listings
    #@listings = Listing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json => @listings }
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @ajxRqst = false
    if(!request.xhr?)
      @ajxRqst = true
    end
    @listing = Listing.find(params[:id])
    puts @listing.inspect

    @favourite = false
    if(!session[:user_id].nil?)
      @user = User.find(session[:user_id])
      if @listing.voted_on_by?(@user)
        @favourite = true
      end
    end
    @pictures = @listing.pictures

    render :html => "show", :layout => @ajxRqst

#    respond_to do |format|
#      #format.html { :layout => false }# show.html.erb
#
#      format.json { render json: @listing }
#    end
  end

  # GET /listings/new
  # GET /listings/new.json
  def new
    @listing = Listing.new

    respond_to do |format|
      format.html  # new.html.erb
      format.json { render json => @listing }
    end
  end

  # GET /listings/1/edit
  def edit
    @listing = Listing.find(params[:id])
  end

  # POST /listings
  # POST /listings.json
  def create
    puts params[:listing]
    params[:listing][:tap_description] = params[:listing][:description].to_s + "-"+params[:listing][:bedrooms].to_s + "Beds-"+ params[:listing][:bathrooms].to_s + "Baths -" + params[:listing][:squarefootage].to_s + "sq.ft"
    @listing = Listing.new(params[:listing])
    @listing.user_id = current_user.id
    if !params[:image_file].nil?
      @uploadimages = Picture.new
      @uploadimages.upload_file_name = params[:image_file].original_filename
      @uploadimages.upload_content_type = params[:image_file].content_type
      @uploadimages.upload_file_size = params[:image_file].size
      @uploadimages.data = params[:image_file].read
    end
    respond_to do |format|
      if @listing.save
        @listings = Listing.where(:user_id => current_user.id)
        if !params[:image_file].nil?
          @uploadimages.listing_id = @listing.id
          @uploadimages.save
        end
        format.html { redirect_to '/mylistings', notice: 'Listing was successfully created.' }
        format.json { render json: @listings, status: :created, location: @listing }
      else
        format.html { render action: "new" }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /listings/1
  # PUT /listings/1.json
  def update
    @listing = Listing.find(params[:id])
    puts "lat long"
    puts @listing.lat
    puts @listing.long

    respond_to do |format|
      if @listing.update_attributes(params[:listing])
        format.html { redirect_to '/mylistings', notice: 'Listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :no_content }
    end
  end


  def home_search
    puts params.inspect
    @recent_listings = Listing.find(:all, :order => "id desc", :limit => 5)
    if(!session[:user_id].nil?)
      @user = User.find(session[:user_id])
      @favs = @user.votes.up.collect { |obj| obj.votable_id }
      @favourite_listings = Listing.find(@favs)
      @searches = @user.searches
      @my_saved_listings = []
      @searches.each do |srch|
        query = []
        query << "listing_type = '#{srch.buy_rent}'" if srch.buy_rent.present?
        query << "price >= #{srch.min_amount}" if srch.min_amount.present?
        query << "price <= #{srch.max_amount}" if srch.max_amount.present?
        query << "bedrooms = #{srch.beds}" if srch.beds.present?
        query << "bathrooms = #{srch.bath}" if srch.bath.present?
        query << "zip = #{srch.zip}" if srch.zip.present?
        #query << "status = true"
        puts srch.days_before.to_s + "days"
        if srch.days_before == "active"
          query << "status = true"
        else
          query << "created_at >= '#{srch.days_before.to_i.days.ago}'"
        end
        puts "Query:" + query.join("AND").to_s
         
           lists1 = Listing.where(query.join(" AND "))
           @my_saved_listings = @my_saved_listings + lists1
           puts @my_saved_listings.inspect
      end
      @my_saved_listings = @my_saved_listings.uniq
    end


    @listings = Listing.where(:listing_type => params[:buy_rent], :status => true)
    puts "*********************"
    puts @listings.inspect
    @listings = @listings.where("price <= ?",params[:amount].to_i) if params[:amount].present?
    puts "****************23*****"
    puts @listings.inspect
  end

  def my_search_listing
    @key_search_listings = Listing.search(params[:key_search]) if params[:key_search].present?
    query = []
    query << "listing_type = '#{params[:buy_rent]}'" if params[:buy_rent].present?
    query << "price >= #{params[:min_amount]}" if params[:min_amount].present?
    query << "price <= #{params[:max_amount]}" if params[:max_amount].present?
    query << "bedrooms = #{params[:bedrooms]}" if params[:bedrooms].present?
    query << "bathrooms = #{params[:bathrooms]}" if params[:bathrooms].present?
    query << "zip = #{params[:zip]}" if params[:zip].present?
    #query << "status = true"
    if params[:days_before] == "active"
      query << "status = true"
    else
      query << "created_at >= '#{params[:days_before].to_i.days.ago}'"
    end

    @listings = Listing.where(query.join(" AND "))
    if params[:key_search].present?       
        @listings  = @listings & @key_search_listings       
    end
    render :layout => false
  end


  def get_contact
    @user = Listing.find(params[:listing_id].to_i).user

    @ud =   UserDetail.find_by_uid(@user.uid)

    render :html => "get_contact", :layout => false
  end

  def show_image
      @image = Picture.find(params[:id])
      send_data @image.data, :type => 'image/png', :disposition => 'inline'
  end

  def add_images

      @pictures = Listing.where(:id => params[:listing_id]).first.pictures
     render :html => "add_images", :layout => false
  end

  def upload_image
    uploadimages = Picture.new
    uploadimages.upload_file_name = params[:image_file].original_filename
    uploadimages.upload_content_type = params[:image_file].content_type
    uploadimages.upload_file_size = params[:image_file].size
    uploadimages.data = params[:image_file].read
    uploadimages.listing_id = params[:listing_id]
    uploadimages.save!
    render :text => uploadimages.id
    #puts "saved"
  end

  def rename
    @listing = Listing.find(params[:id])
    @listing.update_attribute('name', params["listing-name"])
    redirect_to mylistings_path
  end

  def vote_up
    @user = User.find(session[:user_id])
    @listing = Listing.find(params[:lid])
    @listing.liked_by @user
    render :text => "Favourite Added"
  end

  def vote_remove
    @user = User.find(session[:user_id])
    @listing = Listing.find(params[:lid])
    @listing.unvote :voter => @user
    render :text => "Favourite Removed."
  end

  def vote_down
    @user = User.find(session[:user_id])
    @listing = Listing.find(params[:lid])
    @listing.downvote_from @user
    render :text => "disliked"
  end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/add_images.html.erb
<div id="ImageList">
  <%@pictures.each do |p|%>
  <span style="padding:2px"><%= image_tag url_for(:action => 'show_image', :id => p.id), :size => "180x160" %></span>
  
  <% end %>

</div>

<div id="ImageEntry">
  <form class="imageForm">
  <input type="file" id="ImageFile" name="image_file" value = "Select a file" />
  </form>
  <button id="buttonAddImage" value="Add Image" >Add Image </button>
  <%= image_tag 'loading', :id => 'loadingIcon',:style=> 'display:none' %>
</div>

<script>
  $('#ImageFile').change(function(){
            var file = this.files[0];
            name = file.name;
            size = file.size;
            type = file.type;

            if(file.name.length < 1) {
              alert("Please enter a valid file");
              return false;
            }
            else if(file.size > 100000) {
                alert("File is to big");
            }
            else if(file.type != 'image/png' && file.type != 'image/jpg' && !file.type != 'image/gif' && file.type != 'image/jpeg' ) {
                alert("File doesnt match png, jpg or gif");
            }
            else {
                $('#buttonAddImage').click(function(){
                    if($('#ImageFile').val() == ''){
                      alert("please select a file to upload");
                      return false;
                    }
                    var formData = new FormData($('.imageForm')[0]);
                    $('#ImageFile').val('');
                    $('#buttonAddImage').hide();
                    $('#loadingIcon').show()
                    $.ajax({
                        url: '/upload_image?listing_id='+$('#hiddenListingId').val(),  //server script to process data
                        type: 'POST',

                        //Ajax events
                        success: completeHandler = function(data) {
                          $('#buttonAddImage').show();
                          $('#loadingIcon').hide();
                          $('#ImageList').append('<span style="padding:2px"><img width="180" height="160" src="/show_image?id='+data+'" alt="Show_image?id='+data+'" ></span>')
                          $('#ImageFile').val('');
                          alert("Successfully Added Image");
                      },
                      failure: function(){
                        $('#buttonAddImage').show();
                        $('#loadingIcon').hide();
                      },
                        /*error: errorHandler = function() {
                            alert("error");
                        },*/
                        // Form data
                        data: formData,
                        //Options to tell JQuery not to process data or worry about content-type
                        cache: false,
                        contentType: false,
                        processData: false
                    }, 'json');
                });
            }
    });
</script>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/get_contact.html.erb
<div id="detailsDiv">
<% if @ud.profile_public%>
<p>
  <b>Email:</b>
  <%= @ud.email %>
</p>
<p>
  <b>Name:</b>
  <%= @ud.first_name %>
  <nbsp/>
  <%= @ud.last_name %>
</p>
<p>
  <% if !@ud.picture_id.nil? %>
    <b>Picture:</b>
    <%= image_tag url_for(:action => 'show_image', :id => @ud.picture_id, :controller => 'listings'), :size => "100x100" %>
  <% end %>
</p>
<p>
  <b>Address:</b>
  <div>
  	<%= @ud.address1 %>
  	<br/>
  	<%= @ud.address2 %>
  	<br/>
  	<%= @ud.city %>
  	<br/>
  	<%= @ud.zip %>
  </div>
</p>
<p>
  <b>phone:</b>
  <%= @ud.phone %>
</p>
<% else %>
<h2> User is not allowing to share his details. You can drop him a message if you want.</h2>
<br/>
<% end %>
<a href="#" onclick="messageSending_form()"> Send Message</a>
</div>
<div id="sendingForm" style="display:none" >
  <form action="#" name="reply_messsage_form" method="post" remote="true" id="messageForm">
    <%=hidden_field_tag :mesg_id,'',{:id =>"message_id"} %>
    Subject:<%=text_field_tag :subject %>
    <br/>
    Message:<%=text_area :body,'',:rows =>4,:cols=>35 %>
    <div style="float:right">
      <input type="button" value="Post Message" id="replyBtn" />
    </div>
    <%=hidden_field_tag :listing_owner, @user.id,{:id=>"owner_id"} %>
    <%=hidden_field_tag :listing_id, params[:listing_id],{:id=>"listing_id"} %>
  </form>
</div>



<script type="text/javascript">
  function messageSending_form(){
    $("#detailsDiv").hide();
    $("#sendingForm").show();
   
  }

  $(document).ready(function(){
     $("#replyBtn").click(function() {

    var url = "/send_message"; // the script where you handle the form input.

    $.ajax({
           type: "POST",
           url: url,
           data: $("#messageForm").serialize(), // serializes the form's elements.
           success: function(data)
           {

               alert(data); // show response from the php script.
               $( ".selector" ).dialog('close');
           }
             });

        return false; // avoid to execute the actual submit of the form.
    });
  });

</script>

app/views/listings/index.html.erb
<div class="innerPageContent">

  <div class="innerLeft">
    <ul class="leftNav">
      <% @listings.each do |l| %>

        <a href="#" id=<%=l.id%> class="mylistings active" onclick ="showListing(this.id)" ><li><%=l.name%></li></a>

      <% end %>

    </ul>

    <div class="optOne">
      <select>
        <option>For Sale</option>
        <option>For Rent</option>
        <option>Both</option>
      </select>
    </div>
    <div class="optTwo">
      <select>
        <option>Active</option>
        <option>Inactive</option>
        <option>Both</option>
      </select>
    </div>
  </div>
  <img src="/assets/topInnerForm.png" style="margin:0px 0px 0px 10px;"/>
  <div class="innerRight">

    <div class="pageHeading" id="page_heading"><h1>My Listing</h1></div>
    <div class="uname" ><div class="uimage"><img src="/assets/user.png"  /></div><div class="username">Welcome! <%= session[:user_name]%></div></div>

    <div class="clrbth"></div>

    <div class="contentInner" id="result_data">

 <!-- <table>
  <tr>
  	<th>Type</th>
    <th>Price</th>
    <th>Laonpayment</th>
    <th>Bedrooms</th>
    <th>Bathrooms</th>
    <th>Squareft</th>
    <th>Cost/sq</th>
    <th>Type</th>
    <th>Year</th>
    <th>Lotsize</th>
    <th>Daysontapski</th>
    <th>Neighbourhood</th>
    <th>Mls#</th>
    <th>Status</th>
    
  </tr>

<% @listings.each do |listing| %>
  <tr>
  	<td><%= listing.listing_type %></td>
    <td><%= listing.price %></td>
    <td><%= listing.laonpayment %></td>
    <td><%= listing.bedrooms %></td>
    <td><%= listing.bathrooms %></td>
    <td><%= listing.squarefootage %></td>
    <td><%= listing.costpersqft %></td>
    <td><%= listing.adjustment_type %></td>
    <td><%= listing.yearbuilt %></td>
    <td><%= listing.lotsize %></td>
    <td><%= listing.daysontapski %></td>
    <td><%= listing.neighbourhood %></td>
    <td><%= listing.mls %></td>
    <td><%= listing.status %></td>
    <td><%= link_to 'Show', listing %></td>
    <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
    <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table> -->

      <div class="infoAction">

        <div class="contentInnerLeft">
        </div>

        <div class="contentInnerRight">

        </div>


      </div>
      <div class="contentInnerLeft">	 </div>
      <div class="contentInnerRight">
      </div>

      <div class="bottomContent">
      </div>


    </div>


  </div>
  <img src="/assets/bgFormContentBtm.png" style="margin:0px 0px 0px 210px;"/>


  <div class="clrbth"></div>

</div>
</div>

<div id="rename-dialog">
  <form action="" method="post">
  <%= form_tag :url => "", :method => :post do %>
    Name <input type="text" name="listing-name">
    <button type="submit" class="btn-listing-rename">Save</button>
  <% end %>
</div>

<script type="text/javascript">
  $('document').ready(function(){
    $("#my_listings").parent().addClass("active");
    if ($(".mylistings")){
      $(".mylistings")[0].click();
    }
    $("#rename-dialog")
    .dialog(
     {
      bgiframe: true,
      autoOpen: false,
      x:100,
      y:100,
      position:'top',
      width: 320,
      //height: 100,
      modal: true
     }
    );
  });
  function showListing(id)
  {
    var clicked = $("#"+id);
    $.ajax
    ({
      type: "GET",
      url: "/listings/"+id,
      success: function (data){
        $("#result_data").html(data);
        $("#rename-dialog form").attr('action', '/listings/'+ id +'/rename');
        $(".btnStyle.rename").on('click', function() {
          $("#rename-dialog").dialog('open');
          $("#rename-dialog form > input").val($(".mylistings.active li").text());
        });
        $(".mylistings.active").removeClass("active");
        clicked.addClass("active");
      }
    });
  }
</script>

app/views/listings/my_search_listing.html.erb
<div class="container">
<% if @listings.present? %>
  <div id="listingPanelNew">
  <div class="row">
  <% @i = 0 %>
  <% @listings.each do |listing| %>
     <!-- <div class="contentDiv" style="height:auto" > -->
		<% @i = @i+1 %>
	  <div class="span3">
	  <!-- <div class="contentUImage"><img src="/assets/user.png"/></div> -->
			<h3>
		  <%= listing.name %></h3><br/>
		  <h4><%= listing.listing_type %></h4><br/>
                  <span style="height:80px;">
		  <%= listing.tap_description[0..100] %>
                    </span>
		  <br/>
		  <a href="#" id="<%= listing.id %>" class="mylistings" onclick ="showListing(this.id)">Quick View</a>
		  <%=link_to 'Explore', listing%>
	  </div>
	  <% if @i%3 == 0 %>
		</div>
		<br/>
		<div class="row">
	  <% end%>
    <!-- </div> 
    <div class="clrbth"></div> -->
	<% end %>
  </div>
<% end %>
</div>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>
<!-- <%= link_to 'Back', listings_path %> -->
<script>
$('document').ready(function(){
			$("#new_listing").parent().addClass("active");
});
</script>

app/views/listings/show.html.erb
<script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
<%=javascript_include_tag 'smartpaginator' %>
<%=stylesheet_link_tag 'smartpaginator'%>

<% @length = @pictures.length %>
<% @listing_name = @listing.name %>
<script>
  var length = "<%= @length %>";
  $('#black').smartpaginator({ totalrecords: length,
                                        recordsperpage: 1,
                                        datacontainer: 'homeImageHolder',
                                        dataelement: 'div',
                                        theme: 'black' });
  var lname = "<%= @listing_name %>";
  $(document).ready(function(){
     $("#page_heading").find('h1').html(lname);
   });

</script>
<div class="pageHeading"><h1><%=@listing.name %></h1></div>
<p id="notice"><%= notice %></p>
<div class="infoAction">
  
  <div class="contentInnerLeft">
    <div class="homeImageHolder" id="homeImageHolder">
      <% @pictures.each do |p| %>
        <div>
          <%= image_tag url_for(:action => 'show_image', :id => p.id), :size => "300x200" %>
        </div>
    <% end %>

      <!-- <img src="/assets/home.png"/>
      <img src="/assets/pagination.png" style="margin:10px 0px;"/> -->
    </div>
    <div id="black" style="margin: auto;"></div>
  </div>

  <div class="contentInnerRight">
    <div id="editButtonsDiv">
      <input type="button" class="btn-rename" value="Rename"/>
      <!--      <%= link_to 'Modify', edit_listing_path(@listing) %> -->
      <a href=<%=edit_listing_path(@listing) %> ><input type="button" class="btn-modify" value="Modify"/> </a>
      <%= link_to (button_tag "Delete", :class => "btn-delete", :type => "input"),
        listing_path(@listing), :method => :delete, :confirm => "Are you sure?", :rel => "nofollow" %>
	  
      <input type="button" class="btn-event" value="Add Event"/>
    </div>
    <div id="ContactLink" style="display:none" >
      <div>
        
        <% if @favourite %>
          <a href="#" id="voteremove" onclick="voteremove()">
            <image src="/assets/star.jpeg" width="50" height="50" />
          </a>
          <a href="#" id="voteup" onclick="voteup()"  style="display:none">
            <image src="/assets/read-star.png" width="50" height="50" />
          </a>
        <% else %>
          <a href="#" id="voteup" onclick="voteup()" >
            <image src="/assets/read-star.png" width="50" height="50" />
          </a>
        <a href="#" id="voteremove" onclick="voteremove()" style="display:none">
            <image src="/assets/star.jpeg" width="50" height="50" />
          </a>
        <% end %>
        <a href="#" id="votedown" onclick="votedown()" >
            <image src="/assets/block.png" width="50" height="50" />
          </a>
      </div>
      <br/>
      <input type="button" class="btn-contact" value="Contact" onclick="getContactDetails(this.id); return false;"  id=<%=@listing.id%> />
      <div class="selector">
        <div id="divInDialog"></div>
      </div>
    </div>
  </div>


</div>
<div class="contentInnerLeft">
  <div class="well">
    <%= @listing.description %>
  </div>
  <div class="info">
    <div class="left">Listing Type:</div>
    <div class="right"><%= @listing.listing_type %></div>
  </div>

  <div class="info">
    <div class="left">Price</div>
    <div class="right"><%= @listing.price %></div>
  </div>

  <!--<div class="info">
    <div class="left">Loan Payment</div>
    <div class="right"><%= @listing.laonpayment %></div>
  </div> -->

  <div class="info">
    <div class="left">Bedroom</div>
    <div class="right"><%= @listing.bedrooms %></div>
  </div>

  <div class="info">
    <div class="left">Bathrooms</div>
    <div class="right"><%= @listing.bathrooms %></div>
  </div>
  <div class="info">
    <div class="left">Square Footage</div>
    <div class="right"><%= @listing.squarefootage %></div>
  </div>
  <div class="info">
    <div class="left">$/sqft</div>
    <div class="right"><%= @listing.costpersqft %></div>
  </div>

  <div class="info">
    <div class="left">Type</div>
    <div class="right"><%= @listing.adjustment_type %></div>
  </div>

  <div class="info">
    <div class="left">Year Built</div>
    <div class="right"><%= @listing.yearbuilt %></div>
  </div>

  <div class="info">
    <div class="left">Lot Size</div>
    <div class="right"><%= @listing.lotsize %></div>
  </div>

  <div class="info">
    <div class="left">Days on Tapski</div>
    <% diff_days = ((((Time.now - @listing.created_at).abs)/3600)/24).to_i %>
    <% if diff_days < 1  %>
      <% diff_days = "To Day" %>
    <% end %>

    <div class="right"><%= diff_days %></div>
  </div>
  <div class="info">
    <div class="left">Neighborhood</div>
    <div class="right"><%= @listing.neighbourhood %></div>
  </div>
  <div class="info">
    <div class="left">MLS#</div>
    <div class="right"><%= @listing.mls %></div>
  </div>
  <div class="info">
    <div class="left">Status</div>
    <div class="right"><% if @listing.status == true%>
        Active
      <% else %>
        InActive
      <% end %></div>
  </div>
  <div class="info">
    <div id ="map_canvas" style="width:100%;height:200px;border-radius:10px;margin-top:20px;">
    </div>
</div>


</div>

<div class="contentInnerRight" id="rightCheck">
  <div><input type="checkbox" id="activeChk"> <label for="activeChk">Active</label></div>
  <div><input type="checkbox" id="reportChk"> <label for="reportChk">Report this Weekly</label></div>
  <div><input type="checkbox" id="tapsChk"> <label for="tapsChk">Use this listing to search Wanted Taps</label></div>
</div>

  <%=hidden_field_tag :long, @listing.long, {:id=>"longitude"}%>
  <%=hidden_field_tag :lat, @listing.lat, {:id=>"lattitude"}%>
<!-- <div class="bottomContent" id="downLinkAttach">
  
  <div> Link to: <input type="text" /> </div>
  <div>Attach Docs: <input type="file" /></div>
</div> -->


<% @arq = @ajxRqst %>
<script type="text/javascript">

  function voteup(){
    var lid="<%=@listing.id%>"

    $.ajax
    ({
      type: "post",
      url: "/vote_listing?lid="+lid,
      success: function (data){
        $("#voteup").hide();
        $("#voteremove").show();
      }
    });

  }

  function votedown(){
    var lid="<%=@listing.id%>"

    $.ajax
    ({
      type: "post",
      url: "/votedown_listing?lid="+lid,
      success: function (data){
        //$("#voteup").hide();
        //$("#voteremove").show();
      }
    });

  }

  function voteremove(){
    var lid="<%=@listing.id%>";
    $.ajax
    ({
      type: "post",
      url: "/remove_vote_listing?lid="+lid,
      success: function (data){
        $("#voteup").show();
        $("#voteremove").hide();
      }
    });

  }

  $(document).ready(function(){
     var ajaxRequest = <%=  @arq %>;
     if(ajaxRequest == true)
       {
         $(".content").attr("style","height:760px");
         $("#editButtonsDiv").hide();
          $("#rightCheck").hide();
       }
     var map;
      var lat;
      var lng;
    /* HTML 5 geolocation. */

          lat = 40.714623;
          lng = -74.006605;

          var myOptions = {
            zoom: 14,
            center: new google.maps.LatLng(lat, lng),
            mapTypeId: google.maps.MapTypeId.ROADMAP
          };
          directionsDisplay = new google.maps.DirectionsRenderer();
          directionsDisplay.suppressMarkers = true;
          map = new google.maps.Map(document.getElementById('map_canvas'), myOptions);
          var edit_lat= $("#longitude").val();
    var edit_lng  = $("#lattitude").val();
    var marker = new google.maps.Marker({
                            position: new google.maps.LatLng(edit_lat, edit_lng),
                            map: map
                        });
    if((edit_lng.length > 0) || (edit_lat.length > 0))
    {
      marker.setMap(map);
      map.setCenter(new google.maps.LatLng(edit_lat, edit_lng));
    }
  });
</script>