config/routes.rb
Tapski::Application.routes.draw do
  root :to => "home#index"

  resources :listings do
    member do
      post 'rename'
    end
  end

  resources :identities
  match '/save_search', :to => "home#save_search"
  match '/mysearches', :to => "home#mysearches"
  match '/search_with_criteria', :to => "home#search_with_criteria"
  match '/get_search_details', :to => "home#get_search_details"
  match '/mylistings', :to => "listings#index"
  match '/profile', :to => "users#profile"
  resources :users
  match "/save_profile", :to => "users#save_profile"
  match "/login", :to => "sessions#new"
  match "/signout" => "sessions#destroy", :as => :signout
  match '/auth/:provider/callback',  to: 'sessions#create'
  match "/auth/failure", to: "sessions#failure"
  match '/auth/:provider/register',  to: 'users#create'
  match '/edit' =>  'users#edit_profile'
  match '/homesearch' => 'listings#home_search'
  match '/my_search_listing' => 'listings#my_search_listing'

  match '/get_listing_contact' => 'listings#get_contact'
  match '/show_image' => 'listings#show_image'
  match '/add_images' => 'listings#add_images'
  match '/upload_image' => 'listings#upload_image', :via => :post
  match '/messages' => 'users#messages'
  match '/reply_message' => 'users#reply_message'
  match '/send_message' => 'users#send_message'
  match '/delete_message' => 'users#delete_message'
  match '/vote_listing' => 'listings#vote_up'
  match '/remove_vote_listing' => 'listings#vote_remove'
  resources :mysearches

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :require_login, :except => ['index']
  def index
  end

  def save_search
    puts "************"
    puts params.inspect
    @search = Search.new
    @search.user_id = session[:user_id]
    @search.keywords = params[:key_search]
    @search.min_amount = params[:min_amount]
    @search.max_amount = params[:max_amount]
    @search.bath = params[:bathrooms]
    @search.beds = params[:bedrooms]
    @search.buy_rent = params[:buy_rent]
    @search.zip = params[:zip]
    @search.name = params[:name]
    @search.days_before = params[:days_before]
    if @search.save!
      render :text => "successfully saved Search Criteria"
    end
  end

  def mysearches
    @user = User.find(session[:user_id])
    @searches = @user.searches
  end

  def get_search_details
    @search = Search.find(params[:id])
    render :html => "get_search_details", :layout => false
  end

  def search_with_criteria
    puts params.inspect
    @search = Search.find(params[:id])

    @lists_key = []
    if(!@search.keywords.nil? && @search.keywords != '')
      @lists_key = Listing.search(@search.keywords)
    end
#    query = "Select * from LISTINGS where "
#
#    unless @search.buy_rent.blank?
#      query = query + "listing_type= '" + @search.buy_rent + "'"
#    end
#
#    unless @search.max_amount.blank?
#      query = query + " AND price <= " + @search.max_amount.to_s
#    end
#
#    unless @search.min_amount.blank?
#      query = query + " AND price >= " + @search.min_amount.to_s
#    end
#
#    unless @search.beds.blank?
#      query = query + " AND bedrooms = " + @search.beds.to_s
#    end
#
#    unless @search.bath.blank?
#      query = query + " AND bathrooms = " + @search.bath.to_s
#    end
#
#    unless @search.zip.blank?
#      query = query + " AND zip like " + @search.zip.to_s
#    end
#
#    unless @search.days_before.blank?
#      #query = query + " AND created_at >= " + (Time.now - params[:days_before].to_i.days).strftime('%d-%m-%Y').to_s
#    end

    query = []
    query << "listing_type = '#{@search.buy_rent}'" if @search.buy_rent.present?
    query << "price >= #{@search.min_amount}" if @search.min_amount.present?
    query << "price <= #{@search.max_amount}" if @search.max_amount.present?
    query << "bedrooms = #{@search.beds}" if @search.beds.present?
    query << "bathrooms = #{@search.bath}" if @search.bath.present?
    query << "zip = #{@search.zip}" if @search.zip.present?
    #query << "status = true"
    if @search.days_before == "active"
      query << "status = true"
    else
      query << "created_at >= '#{@search.days_before.to_i.days.ago}'"
    end

    puts "sql query: #{query}"
    @listings = Listing.where(query.join(" AND ")) #where(:listing_type => params[:buy_rent]).where("price <= ?",params[:max_amount]).where("price >=",params[:min_amount])

    puts @listings.inspect
    #    render :text => @lists_key.to_s
    render :html => "search_with_criteria", :layout => false
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/get_search_details.html.erb
<div class="contentInnerLeft">
  <h1><% @search.name %> </h1>
  <div class="info">
    <div class="left">KeyWord:</div>
    <div class="right"><%= @search.keywords %></div>
  </div>
  <div class="info">
    <div class="left">Listing Type:</div>
    <div class="right"><%= @search.buy_rent %></div>
  </div>
  <div class="info">
    <div class="left">Min Amount</div>
    <div class="right"><%= @search.min_amount %></div>
  </div>

  <div class="info">
    <div class="left">Max Amount</div>
    <div class="right"><%= @search.max_amount %></div>
  </div>
  <div class="info">
    <div class="left">Beds</div>
    <div class="right"><%= @search.beds %></div>
  </div>
  <div class="info">
    <div class="left">Baths</div>
    <div class="right"><%= @search.bath %></div>
  </div>
  <div class="info">
    <div class="left">Zip</div>
    <div class="right"><%= @search.zip %></div>
  </div>
  <div class="info">
    <div class="left">Show From Last</div>
    <div class="right"><%= @search.days_before %></div>
  </div>
</div>

app/views/home/index.html.erb
<div class="top-section">
<!--Left Block-->
<div class="left-block">
<div class="left-bg"></div>
<div class="cont-heading">
<h3>Tapski connects buyers and sellers with top local real<br />
  estate agents bringing a<br />
  social aspect to the entire experience.</h3>
<p>Receive listings of your choice from thousands of listings posted by qualified real estate agents,  get caught up on the latest real estate advice and<br />
  much more</p>
</div>
<div class="right-bg"></div>
</div>
<!--Right Block-->
<div class="right-block">
<div class="left-bg"></div>
  <div class="theme-img"><img src="/assets/taoski_theme_img.jpg" alt="" width="484" height="313" /></div>
  <div class="right-bg"></div>
</div>
</div>
<!--=============Top Section End=============-->
<!--=============Btom Section=============-->
<div class="btom-section">
<div class="gray-bg-left"></div>
<div class="gray-bg-center">
<a href="/listings/new"><div class="left-section" title="Post a Listing">&nbsp;</div></a>
<a href="/homesearch">
<div class="center-section"><img src="/assets/search_home.jpg" alt="" width="276" height="129" /></div>
<div class="right-section">
<img src="/assets/search.png" alt="" width="100" height="100" />
<!-- <div class="form-bg">
   <form id="form1" name="search_form" method="post" action="/homesearch" style="padding:-10px 0 0 0">
    <p style="margin:-10px 0 0 0;">
      <label>
        <input type="radio" name="buy_rent" value="Rental" id="RadioGroup1_0" checked='checked' />
        <span class="radio-text">Rent</span></label>
        <input name="amount" type="text" class="text-box" placeholder="Maximam Rent" /> 
        <input type="radio" name="buy_rent" value="Sale" id="RadioGroup1_1" />
        <span class="radio-text pad-right">Buy</span></label>
      </label>
      <br />
      <br />
      <label>
        <input name="amount" type="text" class="text-box" placeholder="Maximum Cost" style="width:122px;margin-top:2px;" />
      </label>
      <span style="float:right;padding-right:5px;">
      <input type="submit" value="start finding" /></span>
    </p>
    
  </form>
  </div>-->
</div>
</a>
</div>
<div class="gray-bg-right"></div>
</div>


<script>
$('document').ready(function(){
			$("#home").parent().addClass("active");
                        
});
</script>

app/views/home/mysearches.html.erb
<div class="innerPageContent">
  <div class="innerLeft">
    <% if !@searches.empty? %>
      <div id="listingPanelNew">
        <% @searches.each do |l| %>	  	
          <div class="contentDiv" style="width:150px; height: auto;">
            <ul class="no-list-style">
              <li><%=l.name%></li>
              <li><a href="#" id=<%=l.id%> class="mylistings" onclick ="showSearch(this.id)" >Display Search</a></li>
              <li><%= link_to "Edit Search", edit_mysearch_path(l) %></li>
              <li><a href="#" id=<%=l.id%> class="mylistings" onclick ="searchSave(this.id)">Search with this criteria</a></li>
            </ul>
          </div>
          <div class="clrbth"></div>
          <br/>
          <br/>
        <% end %>
      </div>
    <% end %>
  </div>
  <div id ="listingPanel" style="float: left;">
  </div>
  <div class="clrbth"></div>
  <div class="selector">
    <div id="divInDialog">
    </div>
  </div>
</div>
<script type="text/javascript">
  function searchSave(id){   
    $.ajax
    ({
      type: "POST",
      //data: id,
      url: "/search_with_criteria?id="+id,
      success: function (data){
        $("#listingPanel").html("");
        $('#listingPanel').html(data);
        if (data == '' || data.length < 1) {
              alert("No Results found for the given search criteria.");
          }

      }
    });


  }
function showSearch(id)
    {
    $( ".selector" ).dialog({
      show: {
        effect: "blind",
        duration: 1000
      },
      hide: {
        effect: "explode",
        duration: 1000
      },
      position : 'top',
      title: "Search Details",
      open: function(event, ui) {
        $('#divInDialog').load('/get_search_details?id='+id, function() {
          //alert('Load was performed.');
        });
      }
    });

  }

  

  $('#search').click(function(){
    $.ajax
    ({
      type: "POST",
      data: $("form").serialize(),
      url: "/my_search_listing",
      success: function (data){
        $("#result_data").html("");
        $('#listingPanel').html(data);
        //$('#ListingBack').show();
        if (data == '' || data.length < 1) {
              alert("No Results found for the given search criteria.");
          }

      }
    });

  });

  $(document).ready(function(){
    $("#save_search").click(function() {

       if($("#key_search").val() == "" && $("#min_amount").val() == "" && $("#max_amount").val() == "" && $("#bedrooms").val() == "" && $("#bathrooms").val() == "" && $("#zip").val() == ""){
          alert("Please select the any of the values to save search");
       }
       else{
         $( "#saveForm" ).dialog({
            show: {
              effect: "blind",
              duration: 1000
            },
            hide: {
              effect: "explode",
              duration: 1000
            },
            position : 'top',
            title: "Save Search Criteria"

          });
       }
    });

    $("#save_submit").click(function() {
      var url = "/save_search?name="+$("#save_name").val(); // the script where you handle the form input.

      $.ajax({
             type: "POST",
             url: url,
             data: $("form").serialize(), // serializes the form's elements.
             success: function(data)
             {
                 alert(data); // show response from the php script.
             }
           });

        return false; // avoid to execute the actual submit of the form.
     });

  });


</script>

app/views/home/search_with_criteria.html.erb
<% if !@listings.empty? %>
  <div id="listingPanelNew">
    <div class="row">
      <% @i = 0 %>
      <% @listings.each do |listing| %>
                    <% @i = @i+1 %>
              <div class="span3" style="background-color: #EFE994;">
                            <h3>
                      <%= listing.name %></h3><br/>
                      <h4><%= listing.listing_type %></h4><br/>
                      <%= listing.tap_description[0..100] %>
                      <br/>
                      <a href="#" id="<%= listing.id %>" class="mylistings" onclick ="showListing(this.id)">Quick View</a>
                      <%=link_to 'Explore', listing%>
              </div>
              <% if @i%3 == 0 %>
                    </div>
                    <br/>
                    <div class="row">
              <% end%>
            <% end %>
    </div>

     </div>
<% end %>
    <% if(!params[:key_search].nil? && params[:key_search] != '') %>
      <h1> KEY Search Results </h1>
      <% @lists_key.each do |l| %>
	  	<div class="contentUImage"><img src="/assets/user.png"/></div>
		<div class="contentDiv">Listing <%= l.id%>
			<br/>
			<%=l.listing_type%>
			<br/>
			<a href="#" id=<%=l.id%> class="mylistings" onclick ="showListing(this.id)" ><li>Listing<%=l.id%></li></a>
		</div>
	<div class="clrbth"></div>
	<% end %>
    <% end %>
        
     