config/routes.rb
Tapski::Application.routes.draw do
  root :to => "home#index"

  resources :listings do
    member do
      post 'rename'
    end
  end

  resources :identities
  match '/save_search', :to => "home#save_search"
  match '/mysearches', :to => "home#mysearches"
  match '/search_with_criteria', :to => "home#search_with_criteria"
  match '/get_search_details', :to => "home#get_search_details"
  match '/mylistings', :to => "listings#index"
  match '/profile', :to => "users#profile"
  resources :users
  match "/save_profile", :to => "users#save_profile"
  match "/login", :to => "sessions#new"
  match "/signout" => "sessions#destroy", :as => :signout
  match '/auth/:provider/callback',  to: 'sessions#create'
  match "/auth/failure", to: "sessions#failure"
  match '/auth/:provider/register',  to: 'users#create'
  match '/edit' =>  'users#edit_profile'
  match '/homesearch' => 'listings#home_search'
  match '/my_search_listing' => 'listings#my_search_listing'

  match '/get_listing_contact' => 'listings#get_contact'
  match '/show_image' => 'listings#show_image'
  match '/add_images' => 'listings#add_images'
  match '/upload_image' => 'listings#upload_image', :via => :post
  match '/messages' => 'users#messages'
  match '/reply_message' => 'users#reply_message'
  match '/send_message' => 'users#send_message'
  match '/delete_message' => 'users#delete_message'
  match '/vote_listing' => 'listings#vote_up'
  match '/remove_vote_listing' => 'listings#vote_remove'
  resources :mysearches

end

app/controllers/mysearches_controller.rb
class MysearchesController < ApplicationController
  before_filter :load_search

  def edit
  end

  def update
    if @search.update_attributes(params[:search])
      redirect_to mysearches_path
    else
      render :action => :edit
    end
  end

  private

  def load_search
    @search  = Search.find(params[:id])
  end
end

app/helpers/mysearches_helper.rb
module MysearchesHelper
end

app/views/mysearches/_left_side.html.erb
<div class="innerLeft">
  <div id="listingPanelNew">
    <div class="contentDiv" style="width:150px; height: auto;">
      <ul>
        <li><%= @search.name %></li>
      </ul>
    </div>
  </div>
</div>

app/views/mysearches/edit.html.erb
<div class="innerPageContent">
  <%= render partial: "left_side" %>
  <img src="/assets/topInnerForm.png" style="margin:0px 0px 0px 10px;">
  <div class="innerRight">
    <div class="pageHeading">
      <h1>Edit searches</h1>
    </div>
    <div class="contentInner">
      <%= form_for @search, :url => mysearch_path(@search) do |f| %>
        <div class="form-row">
          <%= f.label "Keyword" %>
          <%= f.text_field :keywords %>
        </div>
        <div class="form-row">
          <%= f.label "Listing Type" %>
          <%= f.radio_button :buy_rent, "Rental" %> 
          <%=  f.label "Rent" %> 
          <%= f.radio_button :buy_rent, "Sale" %>
          <%=  f.label "Buy" %> 
        </div>
        <div class="form-row">
          <%= f.label "Min Amount" %>
          <%= f.select :min_amount, options_for_select([ ['No Min',''],[500,500],[1000,1000],[5000,5000],[10000,10000],[50000,50000] ], @search.min_amount) %>
        </div>
        <div class="form-row">
          <%= f.label "Max Amount" %>
          <%= f.select :max_amount, options_for_select([ ['No Max',''],[500,500],[1000,1000],[5000,5000],[10000,10000],[50000,50000],[100000,100000],[1000000,1000000],[5000000,5000000] ], @search.max_amount) %>
        </div>
        <div class="form-row">
          <%= f.label "Beds" %>
          <%= f.select :beds, options_for_select([["No Pref", ""], 1, 2, 3, 4], @search.beds) %>
        </div>
        <div class="form-row">
          <%= f.label "Bath" %>
          <%= f.select :bath, options_for_select([["No Pref", ""], 1, 2, 3, 4], @search.bath) %>
        </div>
        <div class="form-row">
          <%= f.label "Zip" %>
          <%= f.text_field :zip %>
        </div>
        <div class="form-row">
          <%= f.label "Show From Last" %>
          <%= f.select :days_before, options_for_select([['7 Days', 7],['15 Days', 15],['1 Month',30],['3 Month',90],['1 Year',365],['All Active','active']],
          @search.days_before) %>
        </div>
        <div class="form-row">
          <%= f.submit "Save", :class => "submit" %> 
          <%= link_to "Cancel", mysearches_path, :class => "cancel" %>
        </div>
      <% end %>
    </div>
  </div>
  <img src="/assets/bgFormContentBtm.png" style="margin:0px 0px 0px 210px;"/>
  <div class="clrbth"></div>
</div>